import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "../globals.css";
import {ReactNode} from "react";
import {languages} from "@/app/i18n/settings";
import {notFound} from "next/navigation";
import {getTranslation} from "@/app/i18n";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface LayoutProps {
    children: ReactNode;
    params: Promise<{ locale: string }>;
}

export default async function RootLayout({children, params}: Readonly<LayoutProps>) {
    const p = await params;

    if (!languages.includes(p.locale as any)) {
        notFound();
    }
    const {t} = await getTranslation(p.locale,'default');
    return (
        <html lang={p.locale}>
        <body
            suppressHydrationWarning
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <h1>{t("title")}</h1>
        {children}
        </body>
        </html>
    );
}
